spring:
  datasource:
    url: ${DB_LOCAL}

  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update, none)
      ddl-auto: update #create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  servlet:
    context-path: /api/v1

security:
  jwt:
    token:
      access-token-expiration: 300000
      refresh-token-expiration: 86400000
