spring:
  datasource:
    url: ${DB_LOCAL}

  jpa:
    hibernate:
      ddl-auto: none #create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  servlet:
    context-path: /api/v1

security:
  jwt:
    token:
      secret-key: 9UzXdPjLYKgZeDN2f_k11sODwyrsJd6V3oehyg4z1O0ZsldIDEm37NFGLsl2Gl6IEekMPJxuLHeQp5h2DT2MI2lfT_-1sseEbeNYRFRxbRuH_vBOrd_We2ouLwvgM8Qnt0lrmanmcaj1jqnFVrwRUV1AZh-QFWEIXoNKti4VdXc
      access-token-expiration: 300000
      refresh-token-expiration: 86400000